import java.io.FileOutputStream
import java.net.URL
import java.security.MessageDigest

group = "com.alesdrnz.mpv_audio_kit"
version = "0.4.0"

// AGP and the Kotlin Gradle Plugin are supplied by the consuming app's build
// (and by flutter_tools), so this module declares no buildscript classpath of
// its own — pinning them here would force versions onto the app and, on AGP 9,
// would clash with Built-in Kotlin by holding KGP below the required 2.2.10.
plugins {
    id("com.android.library")
}

// ── Built-in Kotlin migration ───────────────────────────────────────────────
// Flutter 3.44+/AGP 9 provide Kotlin out of the box, and applying the Kotlin
// Gradle Plugin (KGP) ourselves there breaks the build. On AGP < 9 (current
// Flutter) KGP is still required, so apply it conditionally on the AGP major
// version. See: https://docs.flutter.dev/release/breaking-changes/migrate-to-built-in-kotlin/for-plugin-authors
val agpMajor = com.android.Version.ANDROID_GRADLE_PLUGIN_VERSION.substringBefore('.').toInt()
if (agpMajor < 9) {
    apply(plugin = "org.jetbrains.kotlin.android")
}

android {
    namespace = "com.alesdrnz.mpv_audio_kit"

    compileSdk = 36
    ndkVersion = "28.2.13676358"

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    sourceSets {
        getByName("main") {
            java.srcDirs("src/main/kotlin")
        }
        getByName("test") {
            java.srcDirs("src/test/kotlin")
        }
    }

    defaultConfig {
        minSdk = 24

        // ── libmpv NDK Integration ──────────────────────────────────────────
        // This plugin uses libmpv.so loaded via dart:ffi at runtime.
        // The shared libraries are automatically downloaded from GitHub 
        // Releases and placed into src/main/jniLibs during the build.
        ndk {
            abiFilters += listOf("arm64-v8a", "armeabi-v7a", "x86_64")
        }

        // Link CMakeLists for the JNI/NDK wrapper
        externalNativeBuild {
            cmake {
                cppFlags("")
                arguments("-DANDROID_STL=c++_shared")
            }
        }
    }

    externalNativeBuild {
        cmake {
            path = file("src/main/cpp/CMakeLists.txt")
            version = "3.22.1"
        }
    }

    testOptions {
        unitTests {
            isIncludeAndroidResources = true
            all {
                it.useJUnitPlatform()

                it.outputs.upToDateWhen { false }

                it.testLogging {
                    events("passed", "skipped", "failed", "standardOut", "standardError")
                    showStandardStreams = true
                }
            }
        }
    }
}

// Replaces the deprecated `android.kotlinOptions {}` DSL; works identically
// whether KGP is applied by us (AGP < 9) or built in (AGP 9+).
project.extensions.configure(org.jetbrains.kotlin.gradle.dsl.KotlinAndroidProjectExtension::class.java) {
    compilerOptions {
        jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17
    }
}

dependencies {
    // Media3 drives the OS media session (now-playing notification,
    // lock-screen / Android-11+ media controls, hardware & Bluetooth
    // media keys). The custom SimpleBasePlayer adapter is a controller
    // only — libmpv decodes in-process; Media3 never touches audio.
    val media3Version = "1.10.1"
    implementation("androidx.media3:media3-session:$media3Version")
    implementation("androidx.media3:media3-common:$media3Version")

    testImplementation("org.jetbrains.kotlin:kotlin-test")
    testImplementation("org.mockito:mockito-core:5.0.0")
    // JUnit 5 engine for the `useJUnitPlatform()` runner above.
    testImplementation("org.junit.jupiter:junit-jupiter:5.10.2")
}

val MPV_RELEASE_VERSION = "libmpv-r11"
val MPV_BASE_URL = "https://github.com/ales-drnz/mpv_audio_kit/releases/download/${MPV_RELEASE_VERSION}"

val downloadMpvTask = tasks.register("downloadMpvLibraries") {
    // Replace these SHA-256 hashes with the ones generated by scripts/generate_checksums.sh
    val abis = mapOf(
        "arm64-v8a" to mapOf(
            "file" to "libmpv_android-arm64-v8a.so",
            "sha256" to "3bd91566fc75bf2f45827495420e56e61b4ba9bb46889bc00ccf8cecd0e17737"
        ),
        "armeabi-v7a" to mapOf(
            "file" to "libmpv_android-armeabi-v7a.so",
            "sha256" to "609e0910c3ccb8fb5183fb2670eade0060e5cea724d3691f7a2471acc45188d4"
        ),
        "x86_64" to mapOf(
            "file" to "libmpv_android-x86_64.so",
            "sha256" to "c13e36c2e419b56af5e1d01ae821d91e5fe1715d97b945c940b5d570b0fe6065"
        )
    )
    
    doLast {
        val jniLibsDir = file("src/main/jniLibs")
        val abiFilters = android.defaultConfig.ndk.abiFilters.ifEmpty { abis.keys }
        abis.filter { it.key in abiFilters }.forEach { (abi, info) ->
            val filename = info["file"]!!
            val expectedHash = info["sha256"]!!
            val abiDir = file("${jniLibsDir}/${abi}")
            if (!abiDir.exists()) abiDir.mkdirs()
            
            val targetFile = file("${abiDir}/libmpv.so")
            var isValid = false
            
            if (targetFile.exists()) {
                val bytes = targetFile.readBytes()
                val digest = MessageDigest.getInstance("SHA-256").digest(bytes)
                val calculatedHash = digest.joinToString("") { "%02x".format(it) }
                if (calculatedHash == expectedHash) {
                    isValid = true
                } else {
                    println("SHA-256 mismatch for ${abi}. Expected: ${expectedHash}, Got: ${calculatedHash}")
                    targetFile.delete()
                }
            }
            
            if (!isValid) {
                val url = "${MPV_BASE_URL}/${filename}"
                println("Downloading libmpv.so for ${abi} from ${url}")
                try {
                    URL(url).openStream().use { input ->
                        FileOutputStream(targetFile).use { output ->
                            input.copyTo(output)
                        }
                    }
                    val bytes = targetFile.readBytes()
                    val digest = MessageDigest.getInstance("SHA-256").digest(bytes)
                    val calculatedHash = digest.joinToString("") { "%02x".format(it) }
                    
                    if (calculatedHash != expectedHash) {
                        targetFile.delete()
                        throw GradleException("SHA-256 verification failed for downloaded ${filename}!")
                    }
                } catch (e: Exception) {
                    println("Failed to download libmpv.so for ${abi}: ${e.message}")
                    if (targetFile.exists()) targetFile.delete()
                }
            }
        }
    }
}

// The remote download wiring is toggled by the build kit's "Libs" actions:
// active in REMOTE mode (downloadMpvTask fetches each ABI's libmpv.so from
// GitHub when the local jniLibs copy is absent / stale), commented out in LOCAL
// mode (use the bundled jniLibs only, never download). The kit comments /
// uncomments this block — do not hand-edit the mpvkit: markers.
// mpvkit:remote:begin
tasks.configureEach {
    if (name.contains("preBuild") || name.contains("externalNativeBuild")) {
        dependsOn(downloadMpvTask)
    }
}
// mpvkit:remote:end
