// Copyright © 2026 & onwards, Alessandro Di Ronza <ales.drnz@gmail.com>.
// All rights reserved.
// Use of this source code is governed by BSD 3-Clause license
// that can be found in the LICENSE file.
//
// AUTO-GENERATED — do not edit by hand.

library;

/// Names of every typed audio filter the public `AudioEffects`
/// bundle exposes, in declaration order. Kept in `test/` because
/// no production code consumes the list.
const List<String> kAudioFilterNames = [
  'acompressor',
  'acontrast',
  'acrusher',
  'adeclick',
  'adeclip',
  'adecorrelate',
  'adelay',
  'adenorm',
  'aderivative',
  'adrc',
  'adynamicequalizer',
  'adynamicsmooth',
  'aecho',
  'aemphasis',
  'aeval',
  'aexciter',
  'afade',
  'afftdn',
  'afftfilt',
  'aformat',
  'afreqshift',
  'afwtdn',
  'agate',
  'aiir',
  'alimiter',
  'allpass',
  'anequalizer',
  'anlmdn',
  'apad',
  'aphaser',
  'aphaseshift',
  'apsyclip',
  'apulsator',
  'aresample',
  'arnndn',
  'asoftclip',
  'asubboost',
  'asubcut',
  'asupercut',
  'asuperpass',
  'asuperstop',
  'atempo',
  'atilt',
  'bandpass',
  'bandreject',
  'bass',
  'biquad',
  'channelmap',
  'chorus',
  'compand',
  'compensationdelay',
  'crossfeed',
  'crystalizer',
  'dcshift',
  'deesser',
  'dialoguenhance',
  'drmeter',
  'dynaudnorm',
  'earwax',
  'ebur128',
  'equalizer',
  'extrastereo',
  'firequalizer',
  'flanger',
  'haas',
  'hdcd',
  'headphone',
  'highpass',
  'highshelf',
  'loudnorm',
  'lowpass',
  'lowshelf',
  'mcompand',
  'pan',
  'rubberband',
  'silenceremove',
  'speechnorm',
  'stereotools',
  'stereowiden',
  'superequalizer',
  'surround',
  'tiltshelf',
  'treble',
  'tremolo',
  'vibrato',
  'virtualbass',
];
